Pull Request général - Itération 2
Pangkevin/J-Biblio pull request #7
Opened 2019-03-27 15:57 UTC by Pangkevin

Bonjour @oliviercailloux,

Ceci est un pull request général car nos fonctionnalités sont liées. Vous trouverez les fonctionnalités suivantes : 
--> L'implémentation de JPA pour les classes Work, Item, Manifestation, Expression, Person, CorporateBody
--> Mise en place des servlets qui permettent d'ajouter/rechercher en base données ( bdd Wildfly) des personnes(person) et des oeuvres(work). Les deux servlets renvoient la recherche en format JSON.
--> Mise en place d'un parser en JSON-P afin de représenter un objet Work en format JSON.
--> Mise en place d'une interface graphique qui permet de rechercher un Work
--> Mise en place d'un parser en JAX-B pour transformer un objet mods en objet Manifestation.

On vous remercie par avance de votre analyse.

2019-03-27 17:19 UTC, oliviercailloux requested changes
Il faut retirer les id de vos éléments, et les remplacer par des références vers les entités correspondantes et utiliser JPA pour gérer ces relations. Par exemple pas d’idManifestation dans Item, mais vous pouvez inclure dans Item une référence vers Manifestation à la place si c’est utile.

Il faut utliser le schéma mods pour générer automatiquement les classes JAX-B, comme discuté précédemment, et non annoter tout à la main. Voir exemples du cours.

M’expliquer pourquoi vous avez retiré le mécanisme ResponsibleEntity, qui me paraissait bien, et de préférence le restaurer.

Les servlets doivent utiliser JAX-RS pour lire du Json et renvoyer du Json (ou autre format) en utilisant la conversion automatique fournie par le conteneur, voir cours.

2019-03-27 17:19 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jbiblio/j_biblio/basicentities/work/Work.java
> +	@LazyCollection(LazyCollectionOption.FALSE)
Ceci n’est pas adéquat, à retirer.

2019-03-27 17:19 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jbiblio/j_biblio/services/ManifestationUnmarshalling.java
> +			e.printStackTrace();
Ne pas masquer les exceptions. BP Exceptions.

2019-03-27 17:19 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jbiblio/j_biblio/services/WorkService.java
> +	@SuppressWarnings("unchecked")
À éviter absolument, risque d’introduction de bugs très difficiles à débusquer.

2019-03-27 17:19 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jbiblio/j_biblio/servlets/ItemJsonServlet.java
>  				 * Jpa will be implemented in the next sprint
Votre commentaire dit l’inverse, il me semble.

2019-03-27 17:19 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jbiblio/j_biblio/servlets/WorkJsonServlet.java
> +@WebServlet("work")
Utiliser plutôt JAX-RS.

2019-03-27 17:19 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jbiblio/j_biblio/servlets/WorkJsonServlet.java
> +	public String convertToJson(List<Work> listWork) {
Il me semble que vous aviez déjà implémenté la conversion en Json, que fait cette méthode ici ?
Dans tous les cas, elle n’a pas à se trouver à cet endroit.

2019-03-27 17:19 UTC, oliviercailloux commented on src/main/resources/META-INF/persistence.xml
> +		<class>io.github.oliviercailloux.y2018.jbiblio.j_biblio.responsibleentity.Person</class>
Non, ne pas lister tout ça.

2019-03-27 17:19 UTC, oliviercailloux commented on src/main/webapp/index.jsp
> +<%@ page language="java" contentType="text/html; charset=UTF-8"
Non, pas de JSP.

2019-03-29 16:51 UTC, oliviercailloux commented
J’attends vos modifications prenant en compte raisonnablement mes remarques ci-dessus et suivant les discussions en séance. Pour rappel, la partie interface graphique est repoussée en itération 3.

2019-03-29 18:46 UTC, oliviercailloux commented
Oups, j’avais omis votre e-mail du 28 mars demandant des informations concernant JSON. Je regarde ça ce soir ou demain.

2019-04-02 11:01 UTC, Pangkevin commented
@oliviercailloux, pouvons-nous reporter la fonctionnalité de la conversion en format mods pour l'itération 3? On a pris pas mal de temps à résoudre le problème lié à la transformation de l'objet work en Json. On est désolé pour ce retard.

Si oui, pouvez-faire refaire la review pour cette pull request svp?

2019-04-02 15:01 UTC, oliviercailloux requested changes
Je n’ai pas l’impression que mes remarques aient été prises en compte.

Je ne suis pas convaincu par l’utilité de vos annotations XML. Une fct de conversion en XML n’était pas prévue, d’ailleurs. Je vous invite à les retirer, à moins que vous ayez en tête un usage particulier de ce format pour votre itération suivante (ou que vous en fassiez déjà usage, ce qui a pu m’échapper).

2019-04-02 15:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jbiblio/j_biblio/basicentities/work/Work.java
> +	@LazyCollection(LazyCollectionOption.FALSE)
Toujours pas adéquat et toujours à retirer. Et n’utilisez pas une simple `Collection` mais une `List` (par exemple).

2019-04-02 15:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/jbiblio/j_biblio/services/ManifestationUnmarshalling.java
> +			e.printStackTrace();
Ne toujours pas masquer les exceptions.

2019-04-02 15:07 UTC, oliviercailloux commented
Vous me demandez dans votre commentaire de reporter la fct import mods, mais j’imagine que vous désirez aussi reporter la fct json ? Sinon, il faut inclure des tests unitaires qui illustrent l’export et l’import de chacun des quatre objets de base.

2019-04-02 15:08 UTC, oliviercailloux commented
Et vous désirez aussi reporter la création du client, n’est-ce pas ?

2019-04-02 15:53 UTC, Pangkevin commented
@oliviercailloux, justement nous avons utilisé les annotations XML afin que la conversion de l'objet en Json marche et inversement. 

Sans ces annotations, nous obtenons les mêmes erreurs qu'on vous a signalé lors de la précédente séance et par mail.

2019-04-02 16:25 UTC, oliviercailloux commented
Cela me semble totalement insensé. Et comment avez-vous pensé à ça, vous avez vu ce conseil quelque part ? 

Quoi qu’il en soit, merci de tenir compte a minima des commentaires ci-dessus, je validerai alors sans attendre pour ne pas accroitre votre retard. Sachant qu’il faudra pour l’itération 3 fournir également des tests unitaires qui valident le JSON, comme indiqué ci-dessus, car en l’état je ne considère pas la fct comme entièrement implémentée.

2019-04-02 20:51 UTC, Pangkevin commented
@oliviercailloux, on a effectué les corrections pour la BP exception et nous avons enlevé l'annotation @LazyCollection(LazyCollectionOption.FALSE) + changer les collections en liste. 

La conversion en JSON de la classe Work sera livré dans la 3e itérations avec les tests unitaires. 

On vous remercie par avance de votre review.

2019-04-03 17:02 UTC, Pangkevin commented
Bonjour @oliviercailloux, on vous relance pour la review de la pull request. 

On vous remercie par avance de votre analyse.

2019-04-03 20:42 UTC, oliviercailloux approved these changes

2019-04-03 20:52 UTC, merged